<a href="https://colab.research.google.com/github/rahad-1309/3-8-21-pioneer-bank-/blob/master/lab_2_class_part01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np

In [38]:
numbers = np.array([1,2,3,4,5,6])


In [39]:
numbers

array([1, 2, 3, 4, 5, 6])

In [40]:
type(numbers)

numpy.ndarray

In [41]:
array2d = np.array([[2,4,5,6],[2,4,5,6],[2,4,5,6]])
array2d

array([[2, 4, 5, 6],
       [2, 4, 5, 6],
       [2, 4, 5, 6]])

In [42]:
array_3d = np.array([[[2,3,4,5],[2,3,4,5],[2,3,4,5]]])
array_3d

array([[[2, 3, 4, 5],
        [2, 3, 4, 5],
        [2, 3, 4, 5]]])

**array attribute**

In [43]:
intigers = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
intigers

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [44]:
intigers.dtype



dtype('int64')

In [45]:
intigers.ndim

2

In [46]:
intigers.shape

(4, 3)

In [47]:
float = np.array([0.0,0.10,0.2,0.3])
float

array([0. , 0.1, 0.2, 0.3])

In [48]:


float.dtype

dtype('float64')

In [49]:
float.ndim

1

In [50]:
float.shape

(4,)

In [51]:
strings = np.array(['rahat','jim','jaky'])
strings

array(['rahat', 'jim', 'jaky'], dtype='<U5')

In [52]:
strings.dtype

dtype('<U5')

In [53]:
strings.ndim

1

In [54]:
strings.shape

(3,)

In [56]:

p = intigers.reshape(3,2)
p

ValueError: ignored

In [60]:
x = np.arange(5)
x+5

array([5, 6, 7, 8, 9])

In [61]:
x>2

array([False, False, False,  True,  True])